apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZHZ4UlBXTG1zczB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1UQXhNekE0TURsYUZ3MHpNekV5TURjeE16RXpNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1a3hQWjEyUjMyZXNRL2xMVEJ4YUU5TWFNOVgycGRPb0o5MFF1TzRxRVNHNldiMmZGM0NiTjlwNFQKT1Exb3psMlFzYmtxYmkrZ2ZhOEpoOVhnNXE3LzhZYWNKTXpGRHNMK3NuY0FlMUswNDJWWDNhd2d6QjcxQW9Qegp4VjBMY1R2RWhiTWNQN3NpdlhTOS9mMjQvN3Mza1VaanZVd3pRTmZZNjVNRzRvSWtHZlpnRENzT3FPcW45SnIwCkl4TFA0b213c2g1RloyTTNrQy9ZMWRlblVxZ2ZBSzQxTCsrVFlIL1k2VElvRVQrZU9XNzRpYWlPMzlyTk9QV28KNlhEcHlPQnRRMjNsdWwvd2dPdTBCVUJzSEE0UUJuL0s2WjRGU245dHZlTHMvRnpMN2tzRjQ3TExMWUhudGpqZAo1YXlERVFqVEttR2ZCYThkbzhDaWZ2dzk2bkZqQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTdk9CWFZoeXMzRVJFNVliclpxRWZsWmNzeXd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVZ0cjFCcldBLwoyK0FGbktQQ3V0WHhPaXBGTGQzYmp1MmErVU91akJjSVVvbVJhVElRM1djWWVpMkZsY1g3b3QyUnRrMk9qa0lCCmxpdTQ5SzNXeWhiMFUrSjI0TFhwbndiUndFR1ByOGZyMjhqb2tIYVloZzk5ejJaQnNMSUI0NkFscXEwajl1b2YKK2FhbVhNekgwQkNCd0VxSFVnUTAyVWI3TVV6OFlIUE9Kb3pVZFBIVUdsR0xnNzZsWjBhaURlZm1RdWJaU3dxRQp2dlN6NzJZbWJjYmd5TTllWEVrdEhtYzgrRHZNVm9DU1FrNXFKVWFkRGYyQ01LcEFITXYwVHVONUZLdCtPTm4xClZsQjl5WFdVaU53QzFScDVnY1hReGRVcFhLc1pRU0ZhR1F4b2RBaFBGMW9LWGF1VGh1SFBpb2ZkeUZ1WjdlUGYKS3ppM0tZOC9yM2RDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E81F65F134D2E94F151A9DBD04C31C43.yl4.ap-southeast-1.eks.amazonaws.com
  name: dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
contexts:
- context:
    cluster: dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
    user: kasuntharu@dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
  name: kasuntharu@dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
current-context: kasuntharu@dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
kind: Config
preferences: {}
users:
- name: kasuntharu@dev-iq-cluster-dumi.ap-southeast-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - dev-iq-cluster-dumi
      - --region
      - ap-southeast-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
