name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  copy-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: copy to get_metrics_service
        run: cp ./requirements.txt ./get_metrics_service
      - name: copy to post_metrics_service
        run: cp ./requirements.txt ./post_metrics_service


  build:
    needs: copy-requirements
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./metrics_service
        file: ./metrics_service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/metrics_service:latest
        
