name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-service-get:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: copy to get_metrics_service
      run: cp ./requirements.txt ./get_metrics_service

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./get_metrics_service
        file: ./get_metrics_service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/get_metrics_service:latest

  build-service-post:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: copy to post_metrics_service
      run: cp ./requirements.txt ./post_metrics_service

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./post_metrics_service
        file: ./post_metrics_service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/post_metrics_service:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: ['build-service-post','build-service-get']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    - name: Set up Kubernetes context
      run: |
        aws eks --region ap-southeast-1 update-kubeconfig --name dev-iq-cluster-dumi

    - name: restart getmetricsservice
      run: kubectl rollout restart deployment/getmetricsservice

    - name: restart postmetricsservice
      run: kubectl rollout restart deployment/postmetricsservice